# Generated by Django 3.1.1 on 2020-10-29 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctions_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('categorie', models.CharField(choices=[('Hobby', 'HOBBY'), ('Fashion', 'FASHION'), ('Electronics', 'ELECTRONICS'), ('Home', 'HOME')], max_length=20)),
                ('picture', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('text', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auctions.auction')),
            ],
        ),
        migrations.RemoveField(
            model_name='bid',
            name='auction',
        ),
        migrations.DeleteModel(
            name='Auctions',
        ),
        migrations.AddField(
            model_name='bid',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auctions.auction'),
        ),
    ]
