# Generated by Django 3.1.1 on 2020-10-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201029_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='picture',
            field=models.URLField(blank=True),
        ),
    ]
