# Generated by Django 3.1.1 on 2020-10-30 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201029_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='categorie',
            field=models.CharField(choices=[('Ho', 'Hobby'), ('Fa', 'Fashion'), ('El', 'Electronics'), ('Ho', 'Home')], max_length=20),
        ),
    ]
