# Generated by Django 3.1.1 on 2020-10-30 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201030_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='text',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='auction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bid',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auctions.auction'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auctions.auction'),
        ),
    ]
