# Generated by Django 3.1.1 on 2020-10-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201030_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='categorie',
            field=models.CharField(choices=[('Hob', 'Hobby'), ('Fas', 'Fashion'), ('Ele', 'Electronics'), ('Hom', 'Home')], max_length=20),
        ),
    ]
