# Generated by Django 3.1.1 on 2020-10-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201031_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='categorie',
            field=models.CharField(choices=[('Hobbyss', 'Hobby'), ('Fashion', 'Fashion'), ('Electronicsss', 'Electronics'), ('Home', 'Home')], max_length=20),
        ),
    ]
