# Generated by Django 3.1.1 on 2020-11-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auction_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='active',
            field=models.BooleanField(),
        ),
    ]
